name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: mkdir -p ${{ github.workspace }}:/srv/jekyll
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact
    
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'azureanimated'

    # Azure logout 
    - name: logout
      run: |
        az logout
